name: Build and Push Comfy Base Docker Image

on:
  workflow_dispatch:
    inputs:
      base_tag:
        description: 'Tag for the base image'
        required: true
      docker_username:
        description: 'Docker Hub Username'
        required: true
      docker_token:
        description: 'Docker Hub Token'
        required: true

jobs:
  build-and-push-base:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ github.event.inputs.docker_username }}
          password: ${{ github.event.inputs.docker_token }}

      - name: Build and push comfy-base image
        run: |
          docker build -f comfy-base.dockerfile -t ${{ github.event.inputs.docker_username }}/comfy-base:${{ github.event.inputs.base_tag }} .
          docker push ${{ github.event.inputs.docker_username }}/comfy-base:${{ github.event.inputs.base_tag }}
          echo "镜像地址: https://hub.docker.com/r/${DOCKER_USERNAME}/${IMAGE_NAME}/tags"